com.Divan.coordinator.User Class Reference
Public Member Functions
User (String name, String surname, int id, String username, String password)
String getName ()
String getSurname ()
int getId ()
String getUsername ()
String getPassword ()
StudyGroup getGroup ()
void setGroup (StudyGroup group)
Detailed Description
The User class represents a user in the system.
Definition at line 22 of file User.java.
Constructor & Destructor Documentation
User()
com.Divan.coordinator.User.User (String name, String surname, int id, String username, String password)
Constructs a User object with the specified attributes.
Parameters
name The user's name.
surname The user's surname.
id The user's ID.
username The user's username.
password The user's password.
Definition at line 53 of file User.java.
                                                                                       {
        this.name = name;
        this.surname = surname;
        this.id = id;
        this.username = username;
        this.password = password;
    }
Member Function Documentation
getGroup()
StudyGroup com.Divan.coordinator.User.getGroup ()
Gets the study group the user belongs to.
Returns
The study group the user belongs to.
Definition at line 111 of file User.java.
                                 {
        return group;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), com.Divan.coordinator.CoordinatorApp.scheduleSession(), com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu(), com.Divan.coordinator.CoordinatorApp.shareResource(), com.Divan.coordinator.CoordinatorApp.viewDiscussions(), com.Divan.coordinator.CoordinatorApp.viewResourceDetails(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
getId()
int com.Divan.coordinator.User.getId ()
Gets the user's ID.
Returns
The user's ID.
Definition at line 84 of file User.java.
                       {
        return id;
    }
getName()
String com.Divan.coordinator.User.getName ()
Gets the user's name.
Returns
The user's name.
Definition at line 66 of file User.java.
                            {
        return name;
    }
getPassword()
String com.Divan.coordinator.User.getPassword ()
Gets the user's password.
Returns
The user's password.
Definition at line 102 of file User.java.
                                {
        return password;
    }
getSurname()
String com.Divan.coordinator.User.getSurname ()
Gets the user's surname.
Returns
The user's surname.
Definition at line 75 of file User.java.
                               {
        return surname;
    }
getUsername()
String com.Divan.coordinator.User.getUsername ()
Gets the user's username.
Returns
The user's username.
Definition at line 93 of file User.java.
                                {
        return username;
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup(), com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup(), and com.Divan.coordinator.CoordinatorApp.mainMenu().
setGroup()
void com.Divan.coordinator.User.setGroup (StudyGroup group)
Sets the study group for the user.
Parameters
group The study group to set for the user.
Definition at line 120 of file User.java.
                                           {
        this.group = group;
    }
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/User.java