com.Divan.coordinator.Resource Class Reference
Public Member Functions
Resource (String title, String description, String link, StudyGroup group)
String getTitle ()
String getDescription ()
String getLink ()
StudyGroup getGroup ()
void setTitle (String title)
Sets the title of the object.
void setLink (String link)
Sets the link of the object.
void setDescription (String description)
Sets the description of the object.
Detailed Description
The Resource class represents a resource item that can be shared within a study group.
Definition at line 24 of file Resource.java.
Constructor & Destructor Documentation
Resource()
com.Divan.coordinator.Resource.Resource (String title, String description, String link, StudyGroup group)
Constructs a Resource object with the specified details.
Parameters
title The title of the resource
description The description of the resource
link The link associated with the resource
group The study group associated with the resource
Definition at line 63 of file Resource.java.
                                                                                     {
        this.title = title;
        this.description = description;
        this.link = link;
        this.group = group;
        this.resources = new ArrayList<>();
    }
Member Function Documentation
getDescription()
String com.Divan.coordinator.Resource.getDescription ()
Gets the description of the resource.
Returns
The description of the resource
Definition at line 85 of file Resource.java.
                                   {
        return description;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
getGroup()
StudyGroup com.Divan.coordinator.Resource.getGroup ()
Gets the study group associated with the resource.
Returns
The study group associated with the resource
Definition at line 103 of file Resource.java.
                                 {
        return group;
    }
getLink()
String com.Divan.coordinator.Resource.getLink ()
Gets the link associated with the resource.
Returns
The link associated with the resource
Definition at line 94 of file Resource.java.
                            {
        return link;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
getTitle()
String com.Divan.coordinator.Resource.getTitle ()
Gets the title of the resource.
Returns
The title of the resource
Definition at line 76 of file Resource.java.
                             {
        return title;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
setDescription()
void com.Divan.coordinator.Resource.setDescription (String description)
Sets the description of the object.
Parameters
description The new description to be set.
Definition at line 130 of file Resource.java.
                                                   {
        this.description = description;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails().
setLink()
void com.Divan.coordinator.Resource.setLink (String link)
Sets the link of the object.
Parameters
link The new link to be set.
Definition at line 121 of file Resource.java.
                                     {
        this.link = link;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails().
setTitle()
void com.Divan.coordinator.Resource.setTitle (String title)
Sets the title of the object.
Parameters
title The new title to be set.
Definition at line 112 of file Resource.java.
                                       {
        this.title = title;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/Resource.java