com.Divan.coordinator.SessionManager Class Reference
Public Member Functions
SessionManager ()
void addSession (Session session)
List< Session > getSessions ()
void displaySessionsForGroup (StudyGroup group)
Static Public Member Functions
static void writeSessionsToFile (List< Session > sessions)
static List< Session > readSessionsFromFile ()
Static Public Attributes
static final String SESSIONS_FILE = `Sessions.bin`
Detailed Description
The SessionManager class handles the management of sessions in the system.
Definition at line 24 of file SessionManager.java.
Constructor & Destructor Documentation
SessionManager()
com.Divan.coordinator.SessionManager.SessionManager ()
Constructs a new SessionManager object with an empty list of sessions.
Definition at line 37 of file SessionManager.java.
                            {
        this.sessions = new ArrayList<>();
    }
Member Function Documentation
addSession()
void com.Divan.coordinator.SessionManager.addSession (Session session)
Adds a session to the list of sessions.
Parameters
session The session to be added.
Definition at line 46 of file SessionManager.java.
                                            {
        sessions.add(session);
    }
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
displaySessionsForGroup()
void com.Divan.coordinator.SessionManager.displaySessionsForGroup (StudyGroup group)
Displays sessions for a specific study group.
Parameters
group The study group for which sessions will be displayed.
Definition at line 64 of file SessionManager.java.
                                                          {
        System.out.println("Sessions for group " + group.getName() + ":");
        boolean foundSessions = false;
        for (Session session : sessions) {
            if (session.getGroup().getName().equals(group.getName())) {
                foundSessions = true;
                System.out.println("Title: " + session.getTitle());
            }
        }
        if (!foundSessions) {
            System.out.println("Your group doesn't have any session.");
        }
    }
References com.Divan.coordinator.StudyGroup.getName().
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
getSessions()
List<Session> com.Divan.coordinator.SessionManager.getSessions ()
Retrieves the list of sessions.
Returns
The list of sessions.
Definition at line 55 of file SessionManager.java.
                                       {
        return sessions;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
readSessionsFromFile()
static List<Session> com.Divan.coordinator.SessionManager.readSessionsFromFile () [static]
Reads sessions from a file.
Returns
The list of sessions read from the file.
Definition at line 97 of file SessionManager.java.
                                                       {
        if (!file.exists()) {
            System.out.println("Sessions file does not exist.");
            return new ArrayList<>();
        }
        try (ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream(file))) {
            @SuppressWarnings("unchecked")
            List<Session> sessions = (List<Session>) inputStream.readObject();
            System.out.println("Sessions have been loaded from " + SESSIONS_FILE);
            return sessions;
        } catch (Exception ignored) {
            return new ArrayList<>();
        }
    }
References com.Divan.coordinator.SessionManager.SESSIONS_FILE.
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
writeSessionsToFile()
static void com.Divan.coordinator.SessionManager.writeSessionsToFile (List< Session > sessions) [static]
Writes sessions to a file.
Parameters
sessions The list of sessions to be written to the file.
Definition at line 83 of file SessionManager.java.
                                                                   {
        try {
            ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream(file));
            outputStream.writeObject(sessions);
            outputStream.close();
        } catch (Exception ignored) {
        }
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails(), and com.Divan.coordinator.CoordinatorApp.scheduleSession().
Member Data Documentation
SESSIONS_FILE
final String com.Divan.coordinator.SessionManager.SESSIONS_FILE = `Sessions.bin` [static]
The file path for sessions serialization.
Definition at line 26 of file SessionManager.java.
Referenced by com.Divan.coordinator.SessionManager.readSessionsFromFile().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/SessionManager.java