com.Divan.coordinator.StudyGroup Class Reference
Public Member Functions
StudyGroup (String name, String description)
String getName ()
String getDescription ()
List< User > getMembers ()
void addMember (User member)
Static Public Member Functions
static void createStudyGroup (Scanner scanner)
static void viewStudyGroup (Scanner scanner)
Detailed Description
The StudyGroup class represents a study group in the system.
Definition at line 25 of file StudyGroup.java.
Constructor & Destructor Documentation
StudyGroup()
com.Divan.coordinator.StudyGroup.StudyGroup (String name, String description)
Constructs a StudyGroup object with the specified name and description.
Parameters
name The name of the study group.
description The description of the study group.
Definition at line 44 of file StudyGroup.java.
                                                       {
        this.name = name;
        this.description = description;
        this.members = new ArrayList<>();
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup().
Member Function Documentation
addMember()
void com.Divan.coordinator.StudyGroup.addMember (User member)
Adds a member to the study group.
Parameters
member The user to add as a member of the study group.
Definition at line 82 of file StudyGroup.java.
                                       {
        members.add(member);
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup().
createStudyGroup()
static void com.Divan.coordinator.StudyGroup.createStudyGroup (Scanner scanner) [static]
Creates a new study group by taking input from the user.
Parameters
scanner The Scanner object for user input.
Definition at line 96 of file StudyGroup.java.
                                                         {
        CoordinatorApp.clearScreen();
        System.out.println("---- Study Group ----");
        scanner.nextLine();
        // Input group details
        System.out.print("Enter Group Name: ");
        String groupName = scanner.nextLine();
        System.out.print("Enter Group Description: ");
        String groupDescription = scanner.nextLine();
        // Display user IDs and usernames
        Account.displayUsernamesWithIDs();
        List<User> groupMembers = new ArrayList<>();
        while (true) {
            // Select users to add to the group
            System.out.println("Enter user ID to add (or type 'exit' to finish adding users):");
            String input = scanner.nextLine().trim();
            if (input.equalsIgnoreCase("exit")) {
                break; // Exit the loop if user types 'exit'
            }
            try {
                int id = Integer.parseInt(input);
                User user = Account.findUserById(id);
                if (user != null) {
                    if (!groupMembers.contains(user)) {
                        // Add user to the group members list
                        groupMembers.add(user);
                        System.out.println("Added user: " + user.getUsername() + " to the group.");
                    } else {
                        System.out.println("User with ID " + id + " is already in the group.");
                    }
                } else {
                    System.out.println("User with ID " + id + " not found.");
                }
            } catch (NumberFormatException e) {
                System.out.println("Invalid user ID format: " + input);
            }
        }
        // Create the study group with the provided details and members
        StudyGroup studyGroup = new StudyGroup(groupName, groupDescription);
        for (User member : groupMembers) {
            studyGroup.addMember(member);
            member.setGroup(studyGroup);
            Account.saveUsersToFile("users.bin");
        }
        groups1.add(studyGroup);
        FileUtility.writeGroupsToFile(groups1);
        System.out.println("Study group created successfully!");
        System.out.println("1. Create another study group");
        System.out.println("2. Back to menu");
        int choice = scanner.nextInt(); // Assuming getValidChoice is defined elsewhere
        if (choice == 1) {
            createStudyGroup(scanner);
        } else {
            CoordinatorApp.groupManagementMenu(scanner); // Assuming groupManagementMenu is defined elsewhere
        }
    }
References com.Divan.coordinator.StudyGroup.addMember(), com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.Account.displayUsernamesWithIDs(), com.Divan.coordinator.Account.findUserById(), com.Divan.coordinator.User.getUsername(), com.Divan.coordinator.CoordinatorApp.groupManagementMenu(), com.Divan.coordinator.Account.saveUsersToFile(), com.Divan.coordinator.StudyGroup.StudyGroup(), and com.Divan.coordinator.FileUtility.writeGroupsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.groupManagementMenu().
getDescription()
String com.Divan.coordinator.StudyGroup.getDescription ()
Gets the description of the study group.
Returns
The description of the study group.
Definition at line 64 of file StudyGroup.java.
                                   {
        return description;
    }
getMembers()
List<User> com.Divan.coordinator.StudyGroup.getMembers ()
Gets the list of members in the study group.
Returns
The list of members in the study group.
Definition at line 73 of file StudyGroup.java.
                                   {
        return members;
    }
getName()
String com.Divan.coordinator.StudyGroup.getName ()
Gets the name of the study group.
Returns
The name of the study group.
Definition at line 55 of file StudyGroup.java.
                            {
        return name;
    }
Referenced by com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup(), com.Divan.coordinator.ResourceManager.displayResourcesForGroup(), com.Divan.coordinator.SessionManager.displaySessionsForGroup(), com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.viewResourceDetails(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
viewStudyGroup()
static void com.Divan.coordinator.StudyGroup.viewStudyGroup (Scanner scanner) [static]
Displays the study groups for viewing.
Parameters
scanner The Scanner object for user input.
Definition at line 169 of file StudyGroup.java.
                                                       {
        List<StudyGroup> loadedGroups = FileUtility.readGroupsFromFile();
        if (loadedGroups != null && !loadedGroups.isEmpty()) {
            CoordinatorApp.clearScreen();
            ViewGroups.viewGroups(loadedGroups, scanner);
        } else {
            System.out.println("No study groups found.");
            CoordinatorApp.groupManagementMenu(scanner);
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.groupManagementMenu(), com.Divan.coordinator.FileUtility.readGroupsFromFile(), and com.Divan.coordinator.ViewGroups.viewGroups().
Referenced by com.Divan.coordinator.CoordinatorApp.groupManagementMenu().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/StudyGroup.java