com.Divan.coordinator.Account Class Reference
Public Member Functions
Account ()
List< User > getUserList ()
void loadUsersFromFile (String fileName)
void register (Scanner scanner)
User login (Scanner scanner)
User loginMenu (Scanner scanner)
Static Public Member Functions
static void saveUsersToFile (String fileName)
static void displayUsernamesWithIDs ()
static User findUserById (int id)
Detailed Description
The Account class represents user account management and authentication.
Definition at line 25 of file Account.java.
Constructor & Destructor Documentation
Account()
com.Divan.coordinator.Account.Account ()
Constructs an Account object with an empty list of users.
Definition at line 35 of file Account.java.
                     {
        this.userList = new ArrayList<>();
    }
Member Function Documentation
displayUsernamesWithIDs()
static void com.Divan.coordinator.Account.displayUsernamesWithIDs () [static]
Displays the usernames and IDs of all users in the user list.
Definition at line 235 of file Account.java.
                                                 {
        System.out.println("User IDs and Usernames:");
        for (User user : userList) {
            System.out.println("ID: " + user.getId() + " - Username: " + user.getUsername());
        }
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup().
findUserById()
static User com.Divan.coordinator.Account.findUserById (int id) [static]
Finds a user in the user list by their ID.
Parameters
id The ID of the user to find
Returns
The user object if found, or null if not found
Definition at line 248 of file Account.java.
                                            {
        for (User user : userList) {
            if (user.getId() == id) {
                return user; // Found the user with the given ID
            }
        }
        return null; // User with the given ID not found
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup().
getUserList()
List<User> com.Divan.coordinator.Account.getUserList ()
Gets the list of users stored in this account.
Returns
The list of users
Definition at line 44 of file Account.java.
                                    {
        return userList;
    }
loadUsersFromFile()
void com.Divan.coordinator.Account.loadUsersFromFile (String fileName)
Loads the list of users from a file.
Parameters
fileName The name of the file to load users from
Definition at line 84 of file Account.java.
                                                   {
        try {
            File file = new File(fileName);
            if (!file.exists()) {
                System.err.println("Error: File not found - " + fileName);
                return;
            }
            // Read users from file using object deserialization
            try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file))) {
                Object obj = ois.readObject();
                if (obj instanceof List) {
                    userList = (List<User>) obj;
                    System.out.println("Users loaded from file: " + fileName);
                } else {
                    System.err.println("Error: Invalid data format in file - " + fileName);
                }
            }
        } catch (Exception Ignored) {
        }
    }
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
login()
User com.Divan.coordinator.Account.login (Scanner scanner)
Performs user login by verifying username and password.
Parameters
scanner The scanner object for input
Returns
The logged-in user or null if login fails
Definition at line 184 of file Account.java.
                                       {
        scanner.nextLine();
        System.out.println("---- Login ----");
        System.out.print("Username: ");
        String username = scanner.nextLine();
        System.out.print("Password: ");
        String password = scanner.nextLine();
        for (User user : userList) {
            if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
                return user;
            }
        }
        return null; // Login failed
    }
Referenced by com.Divan.coordinator.Account.loginMenu().
loginMenu()
User com.Divan.coordinator.Account.loginMenu (Scanner scanner)
Displays the menu for user registration or login, and handles user input accordingly.
Parameters
scanner The scanner object for input
Returns
The logged-in user
Definition at line 206 of file Account.java.
                                           {
        while (true) {
            CoordinatorApp.clearScreen();
            System.out.println("---- Authentication ----");
            System.out.println("1. Register");
            System.out.println("2. Login");
            int choice = scanner.nextInt();
            switch (choice) {
                case 1:
                    register(scanner);
                    break;
                case 2:
                    User loggedInUser = login(scanner);
                    if (loggedInUser != null) {
                        System.out.println("Login successful.");
                        return loggedInUser;
                    } else {
                        System.out.println("Login failed. Please try again.");
                    }
                    break;
            }
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), and com.Divan.coordinator.Account.login().
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
register()
void com.Divan.coordinator.Account.register (Scanner scanner)
Registers a new user by obtaining user information from the user via console input.
Parameters
scanner The scanner object for input
Definition at line 111 of file Account.java.
                                          {
        CoordinatorApp.clearScreen();
        scanner.nextLine();
        System.out.println("---- Register ----");
        System.out.print("Name: ");
        String name = scanner.nextLine();
        System.out.print("Surname: ");
        String surname = scanner.nextLine();
        int id;
        String username;
        // Check for unique ID
        do {
            System.out.print("ID: ");
            id = scanner.nextInt();
            scanner.nextLine(); // Consume newline character
            if (!isIdUnique(id)) {
                System.out.println("ID already exists. Please choose another one.");
            }
        } while (!isIdUnique(id));
        // Check for unique username
        do {
            System.out.print("Username: ");
            username = scanner.nextLine();
            if (!isUsernameUnique(username)) {
                System.out.println("Username already exists. Please choose another one.");
            }
        } while (!isUsernameUnique(username));
        System.out.print("Password: ");
        String password = scanner.nextLine();
        User account = new User(name, surname, id, username, password);
        userList.add(account); // Add the user to the list
        saveUsersToFile(FILE_PATH); // Save the list to file
        System.out.println("Registration successful!");
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), and com.Divan.coordinator.Account.saveUsersToFile().
saveUsersToFile()
static void com.Divan.coordinator.Account.saveUsersToFile (String fileName) [static]
Saves the list of users to a file.
Parameters
fileName The name of the file to save the users to
Definition at line 53 of file Account.java.
                                                        {
        try {
            // Create or overwrite the file
            File file = new File(fileName);
            if (!file.exists()) {
                if (!file.createNewFile()) {
                    return;
                }
            }
            // Update group references if needed
            for (User user : userList) {
                if (user.getGroup() != null) {
                    user.setGroup(user.getGroup());
                }
            }
            // Write users to file using object serialization
            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file))) {
                oos.writeObject(userList);
            }
        } catch (Exception Ignored) {
        }
    }
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup(), and com.Divan.coordinator.Account.register().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/Account.java