com.Divan.coordinator.ResourceManager Class Reference
Public Member Functions
ResourceManager ()
void addResource (Resource resource)
List< Resource > getResources ()
void displayResourcesForGroup (StudyGroup group)
Static Public Member Functions
static void writeResourcesToFile (List< Resource > resources)
static List< Resource > readResourcesFromFile ()
Static Public Attributes
static final String RESOURCES_FILE = `Resources.bin`
Detailed Description
The ResourceManager class manages the resources in the system.
Definition at line 24 of file ResourceManager.java.
Constructor & Destructor Documentation
ResourceManager()
com.Divan.coordinator.ResourceManager.ResourceManager ()
Constructs a new ResourceManager object.
Definition at line 37 of file ResourceManager.java.
                             {
        this.resources = new ArrayList<>();
    }
Member Function Documentation
addResource()
void com.Divan.coordinator.ResourceManager.addResource (Resource resource)
Adds a resource to the resource list.
Parameters
resource The resource to add
Definition at line 46 of file ResourceManager.java.
                                               {
        resources.add(resource);
    }
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
displayResourcesForGroup()
void com.Divan.coordinator.ResourceManager.displayResourcesForGroup (StudyGroup group)
Displays the resources available for a specific study group.
Parameters
group The study group to display resources for
Definition at line 64 of file ResourceManager.java.
                                                           {
        System.out.println("Resources for group " + group.getName() + ":");
        boolean foundResources = false;
        for (Resource resource : resources) {
            if (resource.getGroup().getName().equals(group.getName())) {
                foundResources = true;
                System.out.println("Title: " + resource.getTitle());
            }
        }
        if (!foundResources) {
            System.out.println("Your group doesn't have any resources.");
        }
    }
References com.Divan.coordinator.StudyGroup.getName().
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails(), and com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
getResources()
List<Resource> com.Divan.coordinator.ResourceManager.getResources ()
Retrieves the list of resources.
Returns
The list of resources
Definition at line 55 of file ResourceManager.java.
                                         {
        return resources;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
readResourcesFromFile()
static List<Resource> com.Divan.coordinator.ResourceManager.readResourcesFromFile () [static]
Reads resources from the file.
Returns
The list of resources read from the file
Definition at line 96 of file ResourceManager.java.
                                                         {
        if (!file.exists()) {
            System.out.println("Resources file does not exist.");
            return new ArrayList<>();
        }
        try (ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream(file))) {
            @SuppressWarnings("unchecked")
            List<Resource> resources = (List<Resource>) inputStream.readObject();
            System.out.println("Resources have been loaded from " + RESOURCES_FILE);
            return resources;
        } catch (Exception Ignored) {
            return new ArrayList<>();
        }
    }
References com.Divan.coordinator.ResourceManager.RESOURCES_FILE.
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
writeResourcesToFile()
static void com.Divan.coordinator.ResourceManager.writeResourcesToFile (List< Resource > resources) [static]
Writes the resources to a file.
Parameters
resources The list of resources to write to the file
Definition at line 83 of file ResourceManager.java.
                                                                      {
        try (ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream(file))) {
            outputStream.writeObject(resources);
            System.out.println("Resources have been saved to " + RESOURCES_FILE);
        } catch (Exception Ignored) {
        }
    }
References com.Divan.coordinator.ResourceManager.RESOURCES_FILE.
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails(), and com.Divan.coordinator.CoordinatorApp.shareResource().
Member Data Documentation
RESOURCES_FILE
final String com.Divan.coordinator.ResourceManager.RESOURCES_FILE = `Resources.bin` [static]
The file path for saving and loading resources.
Definition at line 26 of file ResourceManager.java.
Referenced by com.Divan.coordinator.ResourceManager.readResourcesFromFile(), and com.Divan.coordinator.ResourceManager.writeResourcesToFile().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/ResourceManager.java