com.Divan.coordinator.Session Class Reference
Public Member Functions
Session (String title, String date, StudyGroup group, String description)
String getTitle ()
String getDate ()
StudyGroup getGroup ()
String getDescription ()
void setTitle (String title)
Sets the title of the object.
void setDate (String date)
Sets the date of the object.
void setDescription (String description)
Sets the description of the object.
Detailed Description
The Session class represents a session in the system.
Definition at line 24 of file Session.java.
Constructor & Destructor Documentation
Session()
com.Divan.coordinator.Session.Session (String title, String date, StudyGroup group, String description)
Constructs a new Session object.
Parameters
title The title of the session
date The date of the session
group The study group associated with the session
description The description of the session
Definition at line 51 of file Session.java.
                                                                                    {
        this.title = title;
        this.date = date;
        this.group = group;
        this.description = description;
        this.sessions = new ArrayList<>();
    }
Member Function Documentation
getDate()
String com.Divan.coordinator.Session.getDate ()
Retrieves the date of the session.
Returns
The date of the session
Definition at line 73 of file Session.java.
                            {
        return date;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewSessions().
getDescription()
String com.Divan.coordinator.Session.getDescription ()
Retrieves the description of the session.
Returns
The description of the session
Definition at line 91 of file Session.java.
                                   {
        return description;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewSessions().
getGroup()
StudyGroup com.Divan.coordinator.Session.getGroup ()
Retrieves the study group associated with the session.
Returns
The study group associated with the session
Definition at line 82 of file Session.java.
                                 {
        return group;
    }
getTitle()
String com.Divan.coordinator.Session.getTitle ()
Retrieves the title of the session.
Returns
The title of the session
Definition at line 64 of file Session.java.
                             {
        return title;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.viewSessions().
setDate()
void com.Divan.coordinator.Session.setDate (String date)
Sets the date of the object.
Parameters
date The new date to be set.
Definition at line 109 of file Session.java.
                                     {
        this.date = date;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails().
setDescription()
void com.Divan.coordinator.Session.setDescription (String description)
Sets the description of the object.
Parameters
description The new description to be set.
Definition at line 118 of file Session.java.
                                                   {
        this.description = description;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails().
setTitle()
void com.Divan.coordinator.Session.setTitle (String title)
Sets the title of the object.
Parameters
title The new title to be set.
Definition at line 100 of file Session.java.
                                       {
        this.title = title;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/Session.java