com.Divan.coordinator.CoordinatorApp Class Reference
Static Public Member Functions
static void clearScreen ()
static void mainMenu (Scanner scanner)
static void groupManagementMenu (Scanner scanner)
static void sessionSchedulingMenu (Scanner scanner)
static void scheduleSession (Scanner scanner)
static void viewSessions (Scanner scanner)
static void editSessionDetails (Scanner scanner)
Allows the user to edit details of a session.
static void resourceSharingMenu (Scanner scanner)
static void shareResource (Scanner scanner)
static void viewResourceDetails (Scanner scanner)
static void editResourceDetails (Scanner scanner)
Allows the user to edit details of a resource.
static void discussionBoardMenu (Scanner scanner)
static void createDiscussion (Scanner scanner)
static void viewDiscussions (Scanner scanner)
static void editDiscussionDetails (Scanner scanner)
Allows the user to edit details of a discussion.
static void loadAll (Scanner scanner)
static void main (String[] args)
Static Public Attributes
static User currentUser
static SessionManager sessionManager = new SessionManager()
static ResourceManager resourceManager = new ResourceManager()
static DiscussionManager discussionManager = new DiscussionManager()
static List< Discussion > discussions = new ArrayList<Discussion>()
static List< Resource > resources = new ArrayList<Resource>()
static List< Session > sessions = new ArrayList<Session>()
Detailed Description
CoordinatorApp is the main class that manages the functionality of the coordinator application. This application allows users to manage study groups, schedule sessions, share resources, and participate in discussions.
Definition at line 27 of file CoordinatorApp.java.
Member Function Documentation
clearScreen()
static void com.Divan.coordinator.CoordinatorApp.clearScreen () [static]
Clears the console screen.
Definition at line 58 of file CoordinatorApp.java.
                                     {
        System.out.print("\033[H\033[2J");
        System.out.flush();
    }
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.StudyGroup.createStudyGroup(), com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.groupManagementMenu(), com.Divan.coordinator.Account.loginMenu(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.Account.register(), com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), com.Divan.coordinator.CoordinatorApp.scheduleSession(), com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu(), com.Divan.coordinator.CoordinatorApp.shareResource(), com.Divan.coordinator.CoordinatorApp.viewDiscussions(), com.Divan.coordinator.CoordinatorApp.viewResourceDetails(), com.Divan.coordinator.CoordinatorApp.viewSessions(), and com.Divan.coordinator.StudyGroup.viewStudyGroup().
createDiscussion()
static void com.Divan.coordinator.CoordinatorApp.createDiscussion (Scanner scanner) [static]
Allows the user to create a new discussion by providing a topic. Adds the created discussion to the system and saves it to file.
Parameters
scanner Scanner object for user input
Definition at line 511 of file CoordinatorApp.java.
                                                         {
        clearScreen();
        System.out.println("--- Create Discussion ---");
        // Implement discussion creation logic here
        System.out.println("Enter discussion topic:");
        String topic = scanner.next();
        Discussion discussion = new Discussion(topic, currentUser.getGroup());
        //discussionManager.addDiscussion(discussion);
        System.out.println("Discussion created successfully!");
        discussions.add(discussion);
        DiscussionManager.writeDiscussionsToFile(discussions);
        // After creating discussion, return to discussion board menu
        discussionBoardMenu(scanner);
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.CoordinatorApp.discussions, com.Divan.coordinator.User.getGroup(), and com.Divan.coordinator.DiscussionManager.writeDiscussionsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.discussionBoardMenu().
discussionBoardMenu()
static void com.Divan.coordinator.CoordinatorApp.discussionBoardMenu (Scanner scanner) [static]
Displays the discussion board menu and handles user choices. Allows users to create a new discussion or view existing discussions.
Parameters
scanner Scanner object for user input
Definition at line 459 of file CoordinatorApp.java.
                                                            {
        clearScreen();
        System.out.println("--- Discussion Board Menu ---");
        System.out.println("1. Create Discussion");
        System.out.println("2. View Discussions");
        System.out.println("3. Edit Discussion");
        System.out.println("4. Back to Main Menu");
        int choice = scanner.nextInt();
        switch (choice) {
            case 1:
                if(currentUser.getGroup()!= null)
                {
                    createDiscussion(scanner);
                }
                else {
                System.out.println("You dont have a group");
                discussionBoardMenu(scanner);
                }
                break;
            case 2:
                if(currentUser.getGroup()!= null)
                {
                    viewDiscussions(scanner);
                }
                else {
                System.out.println("You dont have a group");
                discussionBoardMenu(scanner);
                }
                
                break;
            case 3:
                if(currentUser.getGroup()!= null)
                {
                    editDiscussionDetails(scanner);
                }
                else {
                System.out.println("You dont have a group");
                discussionBoardMenu(scanner);
                }
                break;
            case 4:
                mainMenu(scanner);
                break;
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.CoordinatorApp.mainMenu(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.mainMenu(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
editDiscussionDetails()
static void com.Divan.coordinator.CoordinatorApp.editDiscussionDetails (Scanner scanner) [static]
Allows the user to edit details of a discussion.
This method displays the discussions for the current user's group and prompts the user to choose a discussion to edit. Users can edit the topic of the discussion if they have permission.
Parameters
scanner The Scanner object used for input.
Definition at line 576 of file CoordinatorApp.java.
                                                              {
        scanner.nextLine(); // Consume newline character
        clearScreen();
        System.out.println("--- Edit Discussion Details ---");
        discussionManager.displayDiscussionsForGroup(currentUser.getGroup());
        System.out.println("Enter the title of the discussion you want to edit details for (or type 'cancel' to return to the menu):");
        String titleChoice = scanner.nextLine();
        if (titleChoice.equalsIgnoreCase("cancel")) {
            return;
        }
        // Search for the discussion with the specified title and group
        Discussion discussionToEdit = null;
        for (Discussion discussion : discussionManager.getDiscussions()) {
            if (discussion.getTopic().equalsIgnoreCase(titleChoice) && discussion.getGroup().getName().equals(currentUser.getGroup().getName())) {
                discussionToEdit = discussion;
                break;
            }
        }
        // If discussion is found, ask for new details and perform editing
        if (discussionToEdit != null) {
            System.out.println("Enter new topic:");
            String newTopic = scanner.nextLine();
            // Perform editing
            discussionToEdit.setTopic(newTopic);
            DiscussionManager.writeDiscussionsToFile(discussionManager.getDiscussions());
            System.out.println("Discussion topic edited successfully!");
        } else {
            System.out.println("Discussion not found or you don't have access to edit this discussion.");
        }
        // After editing resource details, return to main menu
        scanner.nextLine(); // Consume newline character
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.discussionManager, com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup(), com.Divan.coordinator.DiscussionManager.getDiscussions(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.StudyGroup.getName(), com.Divan.coordinator.Discussion.setTopic(), and com.Divan.coordinator.DiscussionManager.writeDiscussionsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.discussionBoardMenu().
editResourceDetails()
static void com.Divan.coordinator.CoordinatorApp.editResourceDetails (Scanner scanner) [static]
Allows the user to edit details of a resource.
This method displays a list of resources for the current user's group and prompts the user to choose a resource to edit. It then allows the user to edit the resource's title, link, and description.
Parameters
scanner The Scanner object used for input.
Definition at line 410 of file CoordinatorApp.java.
                                                            {
        scanner.nextLine(); // Consume newline character
        clearScreen();
        System.out.println("--- Edit Resource Details ---");
        resourceManager.displayResourcesForGroup(currentUser.getGroup());
        System.out.println("Enter the title of the resource you want to edit details for (or type 'cancel' to return to the menu):");
        String titleChoice = scanner.nextLine();
        if (titleChoice.equalsIgnoreCase("cancel")) {
            return;
        }
        // Search for the resource with the specified title and group
        Resource resourceToEdit = null;
        for (Resource resource : resourceManager.getResources()) {
            if (resource.getTitle().equalsIgnoreCase(titleChoice) && resource.getGroup().getName().equals(currentUser.getGroup().getName())) {
                resourceToEdit = resource;
                break;
            }
        }
        // If resource is found, ask for new details and perform editing
        if (resourceToEdit != null) {
            System.out.println("Enter new title:");
            String newTitle = scanner.nextLine();
            System.out.println("Enter new date:");
            String newDescription = scanner.nextLine();
            System.out.println("Enter new description:");
            String newLink = scanner.nextLine();
            // Perform editing
            resourceToEdit.setTitle(newTitle);
            resourceToEdit.setDescription(newDescription);
            resourceToEdit.setLink(newLink);
            ResourceManager.writeResourcesToFile(resourceManager.getResources());
            System.out.println("Resource details edited successfully!");
        } else {
            System.out.println("Resource not found or you don't have access to edit this resource.");
        }
        // After editing resource details, return to main menu
        scanner.nextLine(); // Consume newline character
        return;
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.ResourceManager.displayResourcesForGroup(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.StudyGroup.getName(), com.Divan.coordinator.ResourceManager.getResources(), com.Divan.coordinator.CoordinatorApp.resourceManager, com.Divan.coordinator.Resource.setDescription(), com.Divan.coordinator.Resource.setLink(), com.Divan.coordinator.Resource.setTitle(), and com.Divan.coordinator.ResourceManager.writeResourcesToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.resourceSharingMenu().
editSessionDetails()
static void com.Divan.coordinator.CoordinatorApp.editSessionDetails (Scanner scanner) [static]
Allows the user to edit details of a session.
This method displays a list of sessions for the current user's group and prompts the user to choose a session to edit. It then allows the user to edit the session's title, date, and description.
Parameters
scanner The Scanner object used for input.
Definition at line 244 of file CoordinatorApp.java.
                                                           {
        scanner.nextLine(); // Consume newline character
        clearScreen();
        System.out.println("--- Edit Session Details ---");
        sessionManager.displaySessionsForGroup(currentUser.getGroup());
        System.out.println("Enter the title of the session you want to edit details for (or type 'cancel' to return to the menu):");
        String titleChoice = scanner.nextLine();
        if (titleChoice.equalsIgnoreCase("cancel")) {
            scanner.nextLine(); // Consume newline character
            return;
        }
        // Search for the session with the specified title and group
        Session sessionToEdit = null;
        for (Session session : sessionManager.getSessions()) {
            if (session.getTitle().equalsIgnoreCase(titleChoice) && session.getGroup().getName().equals(currentUser.getGroup().getName())) {
                sessionToEdit = session;
                break;
            }
        }
        // If session is found, ask for new details and perform editing
        if (sessionToEdit != null) {
            System.out.println("Enter new title:");
            String newTitle = scanner.nextLine();
            System.out.println("Enter new date:");
            String newDate = scanner.nextLine();
            System.out.println("Enter new description:");
            String newDescription = scanner.nextLine();
            // Perform editing
            sessionToEdit.setTitle(newTitle);
            sessionToEdit.setDate(newDate);
            sessionToEdit.setDescription(newDescription);
            SessionManager.writeSessionsToFile(sessionManager.getSessions());
            System.out.println("Session details edited successfully!");
        } else {
            System.out.println("Session not found or you don't have access to edit this session.");
        }
        // After editing session details, return to main menu
        scanner.nextLine(); // Consume newline character
        return;
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.SessionManager.displaySessionsForGroup(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.StudyGroup.getName(), com.Divan.coordinator.SessionManager.getSessions(), com.Divan.coordinator.CoordinatorApp.sessionManager, com.Divan.coordinator.Session.setDate(), com.Divan.coordinator.Session.setDescription(), com.Divan.coordinator.Session.setTitle(), and com.Divan.coordinator.SessionManager.writeSessionsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
groupManagementMenu()
static void com.Divan.coordinator.CoordinatorApp.groupManagementMenu (Scanner scanner) [static]
Displays the group management menu.
Parameters
scanner Scanner object for user input
Definition at line 101 of file CoordinatorApp.java.
                                                            {
        clearScreen();
        System.out.println("--- Group Management Menu ---");
        System.out.println("1. Create Study Group");
        System.out.println("2. View Study Group");
        System.out.println("3. Back to Menu");
        int choice = scanner.nextInt();
        switch (choice) {
            case 1:
                StudyGroup.createStudyGroup(scanner);
                break;
            case 2:
                StudyGroup.viewStudyGroup(scanner);
                break;
            case 3:
                mainMenu(scanner);
                return;
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.StudyGroup.createStudyGroup(), com.Divan.coordinator.CoordinatorApp.mainMenu(), and com.Divan.coordinator.StudyGroup.viewStudyGroup().
Referenced by com.Divan.coordinator.StudyGroup.createStudyGroup(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.ViewGroups.viewGroups(), and com.Divan.coordinator.StudyGroup.viewStudyGroup().
loadAll()
static void com.Divan.coordinator.CoordinatorApp.loadAll (Scanner scanner) [static]
Main load point of the CoordinatorApp program. Initializes the application by loading data and starting the main menu.
Definition at line 618 of file CoordinatorApp.java.
                                                {
        // Load initial data from files
        account.loadUsersFromFile("users.bin");
        discussions = discussionManager.readDiscussionsFromFile();
        resources = resourceManager.readResourcesFromFile();
        sessions = sessionManager.readSessionsFromFile();
        // Add loaded data to respective managers
        if(discussions != null) {
        for (Discussion discussion1 : discussions) {
            discussionManager.addDiscussion(discussion1);
        }
        }
        if(resources != null) {
        for (Resource resource : resources) {
            resourceManager.addResource(resource);
        }
        }
        if(sessions != null) {
        for (Session session : sessions) {
            sessionManager.addSession(session);
        }
        }
        // Update lists with the added data
        discussions = discussionManager.getDiscussions();
        resources = resourceManager.getResources();
        sessions = sessionManager.getSessions();
        // Perform user login and start the main menu
        currentUser = account.loginMenu(scanner);
        mainMenu(scanner);
    }
References com.Divan.coordinator.DiscussionManager.addDiscussion(), com.Divan.coordinator.ResourceManager.addResource(), com.Divan.coordinator.SessionManager.addSession(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.discussionManager, com.Divan.coordinator.CoordinatorApp.discussions, com.Divan.coordinator.DiscussionManager.getDiscussions(), com.Divan.coordinator.ResourceManager.getResources(), com.Divan.coordinator.SessionManager.getSessions(), com.Divan.coordinator.Account.loadUsersFromFile(), com.Divan.coordinator.Account.loginMenu(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.DiscussionManager.readDiscussionsFromFile(), com.Divan.coordinator.ResourceManager.readResourcesFromFile(), com.Divan.coordinator.SessionManager.readSessionsFromFile(), com.Divan.coordinator.CoordinatorApp.resourceManager, com.Divan.coordinator.CoordinatorApp.resources, com.Divan.coordinator.CoordinatorApp.sessionManager, and com.Divan.coordinator.CoordinatorApp.sessions.
Referenced by com.Divan.coordinator.CoordinatorApp.main().
main()
static void com.Divan.coordinator.CoordinatorApp.main (String[] args) [static]
Main entry point of the CoordinatorApp program. Initializes the application by loading data and starting the main menu.
Parameters
args Command line arguments (not used)
Definition at line 659 of file CoordinatorApp.java.
                                           {
        loadAll(scanner);
    }
References com.Divan.coordinator.CoordinatorApp.loadAll().
mainMenu()
static void com.Divan.coordinator.CoordinatorApp.mainMenu (Scanner scanner) [static]
Displays the main menu of the application.
Parameters
scanner Scanner object for user input
Definition at line 67 of file CoordinatorApp.java.
                                                 {
        clearScreen();
        System.out.println("--- Main Menu --- Logged in as: " + currentUser.getUsername());
        System.out.println("1. Group Management");
        System.out.println("2. Session Scheduling");
        System.out.println("3. Resource Sharing");
        System.out.println("4. Discussion Board");
        System.out.println("5. Exit");
        int choice = scanner.nextInt();
        switch (choice) {
            case 1:
                groupManagementMenu(scanner);
                break;
            case 2:
                sessionSchedulingMenu(scanner);
                break;
            case 3:
                resourceSharingMenu(scanner);
                break;
            case 4:
                discussionBoardMenu(scanner);
                break;
            case 5:
                System.out.println("Exiting the program...");
                scanner.close();
                return;
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.User.getUsername(), com.Divan.coordinator.CoordinatorApp.groupManagementMenu(), com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), and com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
Referenced by com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.CoordinatorApp.groupManagementMenu(), com.Divan.coordinator.CoordinatorApp.loadAll(), com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), and com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
resourceSharingMenu()
static void com.Divan.coordinator.CoordinatorApp.resourceSharingMenu (Scanner scanner) [static]
Displays the resource sharing menu and handles user choices. Allows users to share resources or view existing resources.
Parameters
scanner Scanner object for user input
Definition at line 294 of file CoordinatorApp.java.
                                                            {
        clearScreen();
        System.out.println("--- Resource Sharing Menu ---");
        System.out.println("1. Share Resource");
        System.out.println("2. View Resources");
        System.out.println("3. Edit Resources");
        System.out.println("4. Back to Main Menu");
        int choice = scanner.nextInt();
        switch (choice) {
            case 1:
                if(currentUser.getGroup()!= null)
                {
                    shareResource(scanner);
                }
                else {
                System.out.println("You dont have a group");
                resourceSharingMenu(scanner);
                }
                break;
            case 2:
                if(currentUser.getGroup()!= null)
                {
                    viewResourceDetails(scanner);
                }
                else {
                System.out.println("You dont have a group");
                resourceSharingMenu(scanner);
                }
                break;
            case 3:
                if(currentUser.getGroup()!= null)
                {
                    editResourceDetails(scanner);
                }
                else {
                System.out.println("You dont have a group");
                resourceSharingMenu(scanner);
                }
                break;
            case 4:
                mainMenu(scanner);
                break;
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.CoordinatorApp.shareResource(), and com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
Referenced by com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.CoordinatorApp.shareResource(), and com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
scheduleSession()
static void com.Divan.coordinator.CoordinatorApp.scheduleSession (Scanner scanner) [static]
Allows the user to schedule a session.
Parameters
scanner Scanner object for user input
Definition at line 177 of file CoordinatorApp.java.
                                                        {
        clearScreen();
        System.out.println("--- Schedule Session ---");
        // Implement session scheduling logic here
        System.out.println("Enter session title:");
        String title = scanner.next();
        System.out.println("Enter session date:");
        String date = scanner.next();
        System.out.println("Enter session description:");
        String description = scanner.next();
        Session session = new Session(title, date, currentUser.getGroup(), description);
        sessions.add(session);
        SessionManager.writeSessionsToFile(sessions);
        System.out.println("Session scheduled successfully!");
        sessionSchedulingMenu(scanner);
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.CoordinatorApp.sessions, com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu(), and com.Divan.coordinator.SessionManager.writeSessionsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
sessionSchedulingMenu()
static void com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu (Scanner scanner) [static]
Displays the session scheduling menu.
Parameters
scanner Scanner object for user input
Definition at line 126 of file CoordinatorApp.java.
                                                              {
        clearScreen();
        System.out.println("--- Session Scheduling Menu ---");
        System.out.println("1. Schedule Session");
        System.out.println("2. View Sessions");
        System.out.println("3. Edit Sessions");
        System.out.println("4. Back to Main Menu");
        int choice = scanner.nextInt();
        switch (choice) {
            case 1:
                if(currentUser.getGroup()!= null)
                {
                    scheduleSession(scanner);
                }
                else {
                System.out.println("You dont have a group");
                sessionSchedulingMenu(scanner);
                }
                break;
            case 2:
                if(currentUser.getGroup()!= null)
                {
                    viewSessions(scanner);
                }
                else {
                System.out.println("You dont have a group");
                sessionSchedulingMenu(scanner);
              
                }
                break;
            case 3:
                if(currentUser.getGroup()!= null)
                {
                    editSessionDetails(scanner);
                }
                else {
                System.out.println("You dont have a group");
                sessionSchedulingMenu(scanner);
                }
                break;
            case 4:
                mainMenu(scanner);
                break;
        }
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.CoordinatorApp.scheduleSession(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
Referenced by com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.CoordinatorApp.scheduleSession(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
shareResource()
static void com.Divan.coordinator.CoordinatorApp.shareResource (Scanner scanner) [static]
Allows the user to share a resource by providing title, description, and link. Adds the shared resource to the system and saves it to file.
Parameters
scanner Scanner object for user input
Definition at line 345 of file CoordinatorApp.java.
                                                      {
        clearScreen();
        System.out.println("--- Share Resource ---");
        // Implement resource sharing logic here
        System.out.println("Enter resource title:");
        String title = scanner.next();
        System.out.println("Enter resource description:");
        String description = scanner.next();
        System.out.println("Enter resource link:");
        String link = scanner.next();
        Resource resource = new Resource(title, description, link, currentUser.getGroup());
        resources.add(resource);
        ResourceManager.writeResourcesToFile(resources);
        // After sharing resource, return to resource sharing menu
        resourceSharingMenu(scanner);
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.CoordinatorApp.resources, com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), and com.Divan.coordinator.ResourceManager.writeResourcesToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.resourceSharingMenu().
viewDiscussions()
static void com.Divan.coordinator.CoordinatorApp.viewDiscussions (Scanner scanner) [static]
Allows the user to view details of discussions and add comments to them.
Parameters
scanner Scanner object for user input
Definition at line 530 of file CoordinatorApp.java.
                                                        {
        clearScreen();
        System.out.println("--- View Discussions ---");
        // Implement logic to view discussions here
        discussionManager.displayDiscussionsForGroup(currentUser.getGroup()); // Display discussions for the current user's group
        System.out.println("Enter the topic of the discussion you want to comment on (or type 'cancel' to return to the menu):");
        String topicChoice = scanner.nextLine();
        topicChoice = scanner.nextLine();
        if (topicChoice.equalsIgnoreCase("cancel")) {
            discussionBoardMenu(scanner); // Return to discussion board menu if user cancels
            return;
        }
        // Search for the discussion with the specified topic
        Discussion discussionToComment = null;
        for (Discussion discussion : discussionManager.getDiscussions()) {
            if (discussion.getTopic().equalsIgnoreCase(topicChoice)) {
                discussionToComment = discussion;
                break;
            }
        }
        // If discussion is found, prompt for comment and add it
        if (discussionToComment != null) {
            System.out.println("Enter your comment:");
            String comment = scanner.nextLine();
            discussionToComment.addComment(comment);
            discussionManager.writeDiscussionsToFile(discussions);
            System.out.println("Comment added successfully!");
        } else {
            System.out.println("Discussion not found.");
        }
        // After viewing discussions, return to discussion board menu
        discussionBoardMenu(scanner);
    }
References com.Divan.coordinator.Discussion.addComment(), com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.CoordinatorApp.discussionManager, com.Divan.coordinator.CoordinatorApp.discussions, com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup(), com.Divan.coordinator.DiscussionManager.getDiscussions(), com.Divan.coordinator.User.getGroup(), and com.Divan.coordinator.DiscussionManager.writeDiscussionsToFile().
Referenced by com.Divan.coordinator.CoordinatorApp.discussionBoardMenu().
viewResourceDetails()
static void com.Divan.coordinator.CoordinatorApp.viewResourceDetails (Scanner scanner) [static]
Allows the user to view details of a specific resource. Displays the title, description, and link of the resource if found.
Parameters
scanner Scanner object for user input
Definition at line 367 of file CoordinatorApp.java.
                                                            {
        scanner.nextLine();
        clearScreen();
        System.out.println("--- View Resource Details ---");
        resourceManager.displayResourcesForGroup(currentUser.getGroup());
        System.out.println("Enter the title of the resource you want to view details for (or type 'cancel' to return to the menu):");
        String titleChoice = scanner.nextLine();
        if (titleChoice.equalsIgnoreCase("cancel")) {
            resourceSharingMenu(scanner); // Return to resource sharing menu if user cancels
            return;
        }
        // Search for the resource with the specified title and group
        Resource resourceToShow = null;
        for (Resource resource : resourceManager.getResources()) {
            if (resource.getTitle().equalsIgnoreCase(titleChoice) && resource.getGroup().getName().equals(currentUser.getGroup().getName())) {
                resourceToShow = resource;
                break;
            }
        }
        // If resource is found, display its details
        if (resourceToShow != null) {
            System.out.println("Title: " + resourceToShow.getTitle());
            System.out.println("Description: " + resourceToShow.getDescription());
            System.out.println("Link: " + resourceToShow.getLink());
        } else {
            System.out.println("Resource not found or you don't have access to view this resource.");
        }
        // After viewing resource details, return to resource sharing menu
        scanner.nextLine(); // Consume newline character
        return;
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.ResourceManager.displayResourcesForGroup(), com.Divan.coordinator.Resource.getDescription(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.Resource.getLink(), com.Divan.coordinator.StudyGroup.getName(), com.Divan.coordinator.ResourceManager.getResources(), com.Divan.coordinator.Resource.getTitle(), com.Divan.coordinator.CoordinatorApp.resourceManager, and com.Divan.coordinator.CoordinatorApp.resourceSharingMenu().
Referenced by com.Divan.coordinator.CoordinatorApp.resourceSharingMenu().
viewSessions()
static void com.Divan.coordinator.CoordinatorApp.viewSessions (Scanner scanner) [static]
Displays the list of sessions for the user's group and allows viewing session details.
Parameters
scanner Scanner object for user input
Definition at line 198 of file CoordinatorApp.java.
                                                     {
        scanner.nextLine();
        clearScreen();
      
        
        System.out.println("--- View Session Details ---");
        sessionManager.displaySessionsForGroup(currentUser.getGroup());
        System.out.println("Enter the title of the resource you want to view details for (or type 'cancel' to return to the menu):");
        String titleChoice = scanner.nextLine();
        if (titleChoice.equalsIgnoreCase("cancel")) {
            sessionSchedulingMenu(scanner); // Return to resource sharing menu if user cancels
            return;
        }
        // Search for the resource with the specified title and group
        Session sessionToShow = null;
        for (Session session : sessionManager.getSessions()) {
            if (session.getTitle().equalsIgnoreCase(titleChoice) && session.getGroup().getName().equals(currentUser.getGroup().getName())) {
                sessionToShow = session;
                break;
            }
        }
        // If resource is found, display its details
        if (sessionToShow != null) {
            System.out.println("Title: " + sessionToShow.getTitle());
            System.out.println("Date: " + sessionToShow.getDate());
            System.out.println("Description: " + sessionToShow.getDescription());
        } else {
            System.out.println("Session not found or you don't have access to view this session.");
        }
        // After viewing resource details, return to resource sharing menu
        scanner.nextLine(); // Consume newline character
        return;
    }
References com.Divan.coordinator.CoordinatorApp.clearScreen(), com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.SessionManager.displaySessionsForGroup(), com.Divan.coordinator.Session.getDate(), com.Divan.coordinator.Session.getDescription(), com.Divan.coordinator.User.getGroup(), com.Divan.coordinator.StudyGroup.getName(), com.Divan.coordinator.SessionManager.getSessions(), com.Divan.coordinator.Session.getTitle(), com.Divan.coordinator.CoordinatorApp.sessionManager, and com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
Referenced by com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu().
Member Data Documentation
currentUser
User com.Divan.coordinator.CoordinatorApp.currentUser [static]
The currently logged-in user.
Definition at line 35 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.discussionBoardMenu(), com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup(), com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), com.Divan.coordinator.CoordinatorApp.mainMenu(), com.Divan.coordinator.CoordinatorApp.resourceSharingMenu(), com.Divan.coordinator.CoordinatorApp.scheduleSession(), com.Divan.coordinator.CoordinatorApp.sessionSchedulingMenu(), com.Divan.coordinator.CoordinatorApp.shareResource(), com.Divan.coordinator.CoordinatorApp.viewDiscussions(), com.Divan.coordinator.CoordinatorApp.viewResourceDetails(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
discussionManager
DiscussionManager com.Divan.coordinator.CoordinatorApp.discussionManager = new DiscussionManager() [static]
The discussion manager for managing discussions.
Definition at line 44 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
discussions
List<Discussion> com.Divan.coordinator.CoordinatorApp.discussions = new ArrayList<Discussion>() [static]
List of discussions in the application.
Definition at line 47 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
resourceManager
ResourceManager com.Divan.coordinator.CoordinatorApp.resourceManager = new ResourceManager() [static]
The resource manager for managing resources.
Definition at line 41 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.editResourceDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewResourceDetails().
resources
List<Resource> com.Divan.coordinator.CoordinatorApp.resources = new ArrayList<Resource>() [static]
List of resources in the application.
Definition at line 50 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.shareResource().
sessionManager
SessionManager com.Divan.coordinator.CoordinatorApp.sessionManager = new SessionManager() [static]
The session manager for managing sessions.
Definition at line 38 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.editSessionDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewSessions().
sessions
List<Session> com.Divan.coordinator.CoordinatorApp.sessions = new ArrayList<Session>() [static]
List of sessions in the application.
Definition at line 53 of file CoordinatorApp.java.
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.scheduleSession().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/CoordinatorApp.java