com.Divan.coordinator.DiscussionManager Class Reference
Public Member Functions
DiscussionManager ()
void addDiscussion (Discussion discussion)
List< Discussion > getDiscussions ()
void displayDiscussionsForGroup (StudyGroup group)
Static Public Member Functions
static void writeDiscussionsToFile (List< Discussion > discussions)
static List< Discussion > readDiscussionsFromFile ()
Static Public Attributes
static final String DISCUSSIONS_FILE = `Discussions.bin`
Detailed Description
The DiscussionManager class manages discussions, including adding discussions, displaying discussions for a group, and reading/writing discussions to/from a file.
Definition at line 29 of file DiscussionManager.java.
Constructor & Destructor Documentation
DiscussionManager()
com.Divan.coordinator.DiscussionManager.DiscussionManager ()
Constructs a new DiscussionManager object with an empty list of discussions.
Definition at line 39 of file DiscussionManager.java.
                               {
        this.discussions = new ArrayList<>();
    }
Member Function Documentation
addDiscussion()
void com.Divan.coordinator.DiscussionManager.addDiscussion (Discussion discussion)
Adds a discussion to the list of discussions.
Parameters
discussion The discussion to be added
Definition at line 48 of file DiscussionManager.java.
                                                     {
        discussions.add(discussion);
    }
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
displayDiscussionsForGroup()
void com.Divan.coordinator.DiscussionManager.displayDiscussionsForGroup (StudyGroup group)
Displays discussions belonging to a specific study group.
Parameters
group The study group for which discussions are to be displayed
Definition at line 66 of file DiscussionManager.java.
                                                             {
        System.out.println("Discussions for group " + group.getName() + ":");
        boolean foundDiscussion = false;
        for (Discussion discussion : discussions) {
            if (discussion.getGroup().getName().equals(group.getName())) {
                System.out.println("Topic: " + discussion.getTopic());
                System.out.println("Comments:");
                for (String comment : discussion.getComments()) {
                    System.out.println("- " + CoordinatorApp.currentUser.getUsername() + " : " + comment);
                }
                foundDiscussion = true;
            }
            
            else {
                System.out.println("Your group doesn't have any discussions");
                }
        }
        
        
       
    
    }
References com.Divan.coordinator.CoordinatorApp.currentUser, com.Divan.coordinator.StudyGroup.getName(), and com.Divan.coordinator.User.getUsername().
Referenced by com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
getDiscussions()
List<Discussion> com.Divan.coordinator.DiscussionManager.getDiscussions ()
Retrieves the list of discussions.
Returns
The list of discussions
Definition at line 57 of file DiscussionManager.java.
                                             {
        return discussions;
    }
Referenced by com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), com.Divan.coordinator.CoordinatorApp.loadAll(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
readDiscussionsFromFile()
static List<Discussion> com.Divan.coordinator.DiscussionManager.readDiscussionsFromFile () [static]
Reads the list of discussions from a file.
Returns
The list of discussions read from the file
Definition at line 107 of file DiscussionManager.java.
                                                             {
        try (ObjectInputStream inputStream = new ObjectInputStream(new FileInputStream(DISCUSSIONS_FILE))) {
            @SuppressWarnings("unchecked")
            List<Discussion> discussions = (List<Discussion>) inputStream.readObject();
            System.out.println("Discussions have been loaded from " + DISCUSSIONS_FILE);
            return discussions;
        } catch (Exception Ignored) {
            return new ArrayList<>();
        }
    }
References com.Divan.coordinator.DiscussionManager.DISCUSSIONS_FILE.
Referenced by com.Divan.coordinator.CoordinatorApp.loadAll().
writeDiscussionsToFile()
static void com.Divan.coordinator.DiscussionManager.writeDiscussionsToFile (List< Discussion > discussions) [static]
Writes the list of discussions to a file.
Parameters
discussions The list of discussions to be written to file
Definition at line 94 of file DiscussionManager.java.
                                                                            {
        try (ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream(DISCUSSIONS_FILE))) {
            outputStream.writeObject(discussions);
            System.out.println("Discussions have been saved to " + DISCUSSIONS_FILE);
        } catch (Exception Ignored) {
        }
    }
References com.Divan.coordinator.DiscussionManager.DISCUSSIONS_FILE.
Referenced by com.Divan.coordinator.CoordinatorApp.createDiscussion(), com.Divan.coordinator.CoordinatorApp.editDiscussionDetails(), and com.Divan.coordinator.CoordinatorApp.viewDiscussions().
Member Data Documentation
DISCUSSIONS_FILE
final String com.Divan.coordinator.DiscussionManager.DISCUSSIONS_FILE = `Discussions.bin` [static]
The file path for storing discussions.
Definition at line 31 of file DiscussionManager.java.
Referenced by com.Divan.coordinator.DiscussionManager.readDiscussionsFromFile(), and com.Divan.coordinator.DiscussionManager.writeDiscussionsToFile().
The documentation for this class was generated from the following file:
coordinator-app/src/main/java/com/Divan/coordinator/DiscussionManager.java